### ISSUE TITLE
Alerts for KubeSchedulerDown, KubeProxyDown, KubeControllerManagerDown keep firing

### ISSUE THREAD

**Issue by javydekoning** [javydekoning/homelab#1184]
adding to `defaultRules.disable` didn't work. See: 

https://github.com/prometheus-community/helm-charts/issues/1718

for details

**Comment by javydekoning** [comment]
Fixed using:

```yaml
defaultRules:
  rules:
    # Disable KubeSchedulerDown, KubeProxyDown, KubeControllerManagerDown
    # because running in k3s
    kubeControllerManager: false
    kubeProxy: false
    kubeSchedulerAlerting: false
kubeProxy:
  enabled: false
kubeControllerManager:
  enabled: false
```
